import type { Client, Ticket, MockUser, ClientUser, Company } from '@/types'

// Empresas de prueba
export const mockCompanies: Company[] = [
  {
    id: 1,
    name: 'Empresa A S.L.',
    description: 'Empresa líder en soluciones tecnológicas empresariales',
    contact_email: 'contacto@empresa-a.com',
    contact_phone: '+34 900 123 456',
    address: 'Calle Principal 123, 28001 Madrid',
    website: 'https://www.empresa-a.com',
    created_at: '2024-01-01T08:00:00Z',
    updated_at: '2024-01-01T08:00:00Z'
  },
  {
    id: 2,
    name: 'TechCorp Solutions',
    description: 'Consultoría tecnológica y desarrollo de software',
    contact_email: 'info@techcorp.com',
    contact_phone: '+34 900 654 321',
    address: 'Avenida Tecnológica 456, 08001 Barcelona',
    website: 'https://www.techcorp.com',
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-02-15T12:30:00Z'
  },
  {
    id: 3,
    name: 'Freelancer Independiente',
    description: 'Servicios de consultoría freelance especializada',
    contact_email: 'contacto@freelancer.com',
    contact_phone: '+34 900 555 789',
    address: 'Plaza Mayor 789, 46001 Valencia',
    website: 'https://www.freelancer.com',
    created_at: '2024-01-10T12:00:00Z',
    updated_at: '2024-01-10T12:00:00Z'
  },
  {
    id: 4,
    name: 'StartUp Innovadora',
    description: 'Startup enfocada en innovación y tecnología emergente',
    contact_email: 'hello@startup.es',
    contact_phone: '+34 900 777 888',
    address: 'Calle Innovación 321, 41001 Sevilla',
    website: 'https://www.startup.es',
    created_at: '2024-02-01T09:00:00Z',
    updated_at: '2024-03-01T14:00:00Z'
  },
  {
    id: 5,
    name: 'Consulting Pro',
    description: 'Consultoría profesional y servicios empresariales',
    contact_email: 'info@consulting.com',
    contact_phone: '+34 900 444 555',
    address: 'Paseo Consultoría 654, 29001 Málaga',
    website: 'https://www.consulting.com',
    created_at: '2024-02-20T11:00:00Z',
    updated_at: '2024-02-20T11:00:00Z'
  }
]

// Datos de prueba para el sistema de tickets
export const mockClients: Client[] = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juan.perez@empresa-a.com',
    phone: '+34 123 456 789',
    company_id: 1,
    address: 'Calle Principal 123, 28001 Madrid',
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-15T10:30:00Z',
    company: mockCompanies[0]
  },
  {
    id: 2,
    name: 'María García',
    email: 'maria.garcia@techcorp.com',
    phone: '+34 987 654 321',
    company_id: 2,
    address: 'Avenida Tecnológica 456, 08001 Barcelona',
    created_at: '2024-01-20T14:15:00Z',
    updated_at: '2024-02-10T16:45:00Z',
    company: mockCompanies[1]
  },
  {
    id: 3,
    name: 'Carlos López',
    email: 'carlos.lopez@freelancer.com',
    phone: '+34 555 123 456',
    company_id: 3,
    address: 'Plaza Mayor 789, 46001 Valencia',
    created_at: '2024-02-01T09:20:00Z',
    updated_at: '2024-02-01T09:20:00Z',
    company: mockCompanies[2]
  },
  {
    id: 4,
    name: 'Ana Martínez',
    email: 'ana.martinez@startup.es',
    phone: '+34 666 777 888',
    company_id: 4,
    address: 'Calle Innovación 321, 41001 Sevilla',
    created_at: '2024-02-15T11:30:00Z',
    updated_at: '2024-03-01T13:15:00Z',
    company: mockCompanies[3]
  },
  {
    id: 5,
    name: 'Roberto Sánchez',
    email: 'roberto.sanchez@consulting.com',
    phone: '+34 444 555 666',
    company_id: 5,
    address: 'Paseo Consultoría 654, 29001 Málaga',
    created_at: '2024-03-01T08:45:00Z',
    updated_at: '2024-03-01T08:45:00Z',
    company: mockCompanies[4]
  },
  {
    id: 6,
    name: 'Pedro Rodríguez',
    email: 'pedro.rodriguez@empresa-a.com',
    phone: '+34 111 222 333',
    company_id: 1,
    address: 'Calle Secundaria 456, 28002 Madrid',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
    company: mockCompanies[0]
  },
  {
    id: 7,
    name: 'Laura Fernández',
    email: 'laura.fernandez@techcorp.com',
    phone: '+34 999 888 777',
    company_id: 2,
    address: 'Rambla Tecnológica 789, 08002 Barcelona',
    created_at: '2024-03-15T14:30:00Z',
    updated_at: '2024-03-15T14:30:00Z',
    company: mockCompanies[1]
  }
]

export const mockTickets: Ticket[] = [
  // ===== EMPRESA A S.L. (company_id: 1) - Clientes: Juan Pérez (id: 1), Pedro Rodríguez (id: 6) =====
  {
    id: 1,
    title: 'Sistema de facturación no genera PDFs',
    description: 'Desde ayer el sistema de facturación no está generando los archivos PDF correctamente. Los clientes están reportando que no pueden descargar sus facturas.',
    status: 'open',
    priority: 'high',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-07-03T08:30:00Z',
    updated_at: '2024-07-03T08:30:00Z',
    client: mockClients[0],
    category: 'technical_issue'
  },
  {
    id: 2,
    title: 'Migración a nueva versión del sistema',
    description: 'Actualizar el sistema a la versión 2.0 con las nuevas funcionalidades solicitadas. Incluye migración de datos y pruebas completas.',
    status: 'closed',
    priority: 'medium',
    client_id: 1,
    assigned_to: 'user-456',
    created_at: '2024-06-15T09:00:00Z',
    updated_at: '2024-06-30T17:30:00Z',
    client: mockClients[0],
    assigned_user: { email: 'admin@empresa.com' },
    category: 'technical_issue'
  },
  {
    id: 3,
    title: 'Configuración de backup automático',
    description: 'Necesitamos configurar backups automáticos para la base de datos. Empresa A requiere backup diario con retención de 30 días.',
    status: 'open',
    priority: 'medium',
    client_id: 6,
    assigned_to: null,
    created_at: '2024-07-04T09:30:00Z',
    updated_at: '2024-07-04T09:30:00Z',
    client: mockClients[5],
    category: 'feature_request'
  },
  {
    id: 4,
    title: 'Error en módulo de inventario',
    description: 'El módulo de inventario no actualiza correctamente las cantidades cuando se realizan ventas. Problema crítico para el negocio.',
    status: 'in_progress',
    priority: 'high',
    client_id: 1,
    assigned_to: 'user-101',
    created_at: '2024-07-02T14:20:00Z',
    updated_at: '2024-07-03T10:15:00Z',
    client: mockClients[0],
    assigned_user: { email: 'dev@empresa.com' },
    category: 'technical_issue'
  },
  {
    id: 5,
    title: 'Integración con sistema contable',
    description: 'Solicitud de integración con el software contable ContaPlus para automatizar el traspaso de facturas.',
    status: 'open',
    priority: 'medium',
    client_id: 6,
    assigned_to: null,
    created_at: '2024-07-01T16:45:00Z',
    updated_at: '2024-07-01T16:45:00Z',
    client: mockClients[5],
    category: 'feature_request'
  },
  {
    id: 6,
    title: 'Problema con envío de emails masivos',
    description: 'Los emails masivos de marketing no se están enviando correctamente. Solo llegan algunos.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 1,
    assigned_to: 'user-202',
    created_at: '2024-06-28T11:30:00Z',
    updated_at: '2024-07-01T09:20:00Z',
    client: mockClients[0],
    assigned_user: { email: 'support@empresa.com' },
    category: 'technical_issue'
  },
  {
    id: 7,
    title: 'Optimización de consultas lentas',
    description: 'Las consultas de reportes mensuales están tardando más de 5 minutos. Necesitamos optimización urgente.',
    status: 'closed',
    priority: 'high',
    client_id: 6,
    assigned_to: 'user-303',
    created_at: '2024-06-20T08:15:00Z',
    updated_at: '2024-06-25T14:30:00Z',
    client: mockClients[5],
    assigned_user: { email: 'dba@empresa.com' },
    category: 'technical_issue'
  },
  {
    id: 8,
    title: 'Actualización de certificados SSL',
    description: 'Los certificados SSL van a expirar en 15 días. Necesitamos renovarlos antes de que caduquen.',
    status: 'open',
    priority: 'high',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-07-04T07:00:00Z',
    updated_at: '2024-07-04T07:00:00Z',
    client: mockClients[0],
    category: 'technical_issue'
  },
  {
    id: 9,
    title: 'Implementar autenticación de dos factores',
    description: 'Por seguridad, necesitamos implementar 2FA para todos los usuarios administradores del sistema.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 6,
    assigned_to: 'user-404',
    created_at: '2024-06-30T10:00:00Z',
    updated_at: '2024-07-02T15:30:00Z',
    client: mockClients[5],
    assigned_user: { email: 'security@empresa.com' },
    category: 'feature_request'
  },
  {
    id: 10,
    title: 'Error en cálculo de comisiones',
    description: 'El sistema está calculando mal las comisiones de ventas. Los porcentajes no coinciden con los configurados.',
    status: 'open',
    priority: 'high',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-07-03T13:45:00Z',
    updated_at: '2024-07-03T13:45:00Z',
    client: mockClients[0],
    category: 'technical_issue'
  },
  {
    id: 11,
    title: 'Migrar base de datos a servidor más potente',
    description: 'La base de datos actual se está quedando pequeña. Necesitamos migrar a un servidor con más capacidad.',
    status: 'open',
    priority: 'low',
    client_id: 6,
    assigned_to: null,
    created_at: '2024-06-25T09:20:00Z',
    updated_at: '2024-06-25T09:20:00Z',
    client: mockClients[5]
  },
  {
    id: 12,
    title: 'Configurar monitoreo del sistema',
    description: 'Implementar alertas automáticas para supervisar el rendimiento del sistema 24/7.',
    status: 'closed',
    priority: 'medium',
    client_id: 1,
    assigned_to: 'user-505',
    created_at: '2024-06-18T14:00:00Z',
    updated_at: '2024-06-22T16:45:00Z',
    client: mockClients[0],
    assigned_user: { email: 'ops@empresa.com' }
  },
  {
    id: 13,
    title: 'Error en generación de reportes de ventas',
    description: 'Los reportes de ventas no incluyen las ventas realizadas después de las 18:00 horas.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 6,
    assigned_to: 'user-606',
    created_at: '2024-07-01T12:30:00Z',
    updated_at: '2024-07-03T08:15:00Z',
    client: mockClients[5],
    assigned_user: { email: 'analyst@empresa.com' }
  },
  {
    id: 14,
    title: 'Implementar módulo de gestión de proyectos',
    description: 'Solicitud de nuevo módulo para gestionar proyectos internos con timeline y asignación de recursos.',
    status: 'open',
    priority: 'low',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-06-28T15:20:00Z',
    updated_at: '2024-06-28T15:20:00Z',
    client: mockClients[0]
  },
  {
    id: 15,
    title: 'Problema con sincronización de datos',
    description: 'Los datos entre el sistema principal y el CRM no se están sincronizando correctamente.',
    status: 'open',
    priority: 'high',
    client_id: 6,
    assigned_to: null,
    created_at: '2024-07-04T11:00:00Z',
    updated_at: '2024-07-04T11:00:00Z',
    client: mockClients[5]
  },
  {
    id: 16,
    title: 'Actualizar documentación técnica',
    description: 'La documentación técnica está desactualizada y necesita revisión completa.',
    status: 'in_progress',
    priority: 'low',
    client_id: 1,
    assigned_to: 'user-707',
    created_at: '2024-06-26T10:45:00Z',
    updated_at: '2024-07-02T14:20:00Z',
    client: mockClients[0],
    assigned_user: { email: 'tech-writer@empresa.com' }
  },
  {
    id: 17,
    title: 'Error en carga de archivos grandes',
    description: 'No se pueden subir archivos de más de 10MB al sistema. Error de timeout.',
    status: 'closed',
    priority: 'medium',
    client_id: 6,
    assigned_to: 'user-808',
    created_at: '2024-06-22T09:15:00Z',
    updated_at: '2024-06-24T11:30:00Z',
    client: mockClients[5],
    assigned_user: { email: 'dev@empresa.com' }
  },
  {
    id: 18,
    title: 'Configurar entorno de desarrollo',
    description: 'Necesitamos un entorno de desarrollo separado para pruebas antes de subir a producción.',
    status: 'open',
    priority: 'medium',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-07-02T16:00:00Z',
    updated_at: '2024-07-02T16:00:00Z',
    client: mockClients[0]
  },
  {
    id: 19,
    title: 'Implementar cache para mejorar rendimiento',
    description: 'Las páginas tardan mucho en cargar. Implementar sistema de cache Redis.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 6,
    assigned_to: 'user-909',
    created_at: '2024-06-29T13:30:00Z',
    updated_at: '2024-07-03T09:45:00Z',
    client: mockClients[5],
    assigned_user: { email: 'performance@empresa.com' }
  },
  {
    id: 20,
    title: 'Error en módulo de facturación electrónica',
    description: 'Las facturas electrónicas no se están enviando al SAT correctamente.',
    status: 'open',
    priority: 'high',
    client_id: 1,
    assigned_to: null,
    created_at: '2024-07-04T14:15:00Z',
    updated_at: '2024-07-04T14:15:00Z',
    client: mockClients[0]
  },

  // ===== TECHCORP SOLUTIONS (company_id: 2) - Clientes: María García (id: 2), Laura Fernández (id: 7) =====
  {
    id: 21,
    title: 'Solicitud de reporte de ventas mensuales',
    description: 'Necesitamos agregar un nuevo reporte que muestre las ventas por mes y por producto. El reporte debe incluir gráficos interactivos.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 2,
    assigned_to: 'user-123',
    created_at: '2024-07-01T14:20:00Z',
    updated_at: '2024-07-02T16:45:00Z',
    client: mockClients[1],
    assigned_user: { email: 'desarrollador@empresa.com' },
    category: 'feature_request'
  },
  {
    id: 22,
    title: 'Problema con envío de emails',
    description: 'Los emails de notificación no se están enviando. Los usuarios no reciben confirmaciones de sus acciones.',
    status: 'open',
    priority: 'high',
    client_id: 2,
    assigned_to: 'user-101',
    created_at: '2024-07-03T12:30:00Z',
    updated_at: '2024-07-03T12:30:00Z',
    client: mockClients[1],
    assigned_user: { email: 'support@empresa.com' },
    category: 'technical_issue'
  },
  {
    id: 23,
    title: 'Implementar dashboards ejecutivos',
    description: 'TechCorp solicita dashboards personalizados para la gerencia con métricas de KPI en tiempo real.',
    status: 'in_progress',
    priority: 'high',
    client_id: 7,
    assigned_to: 'user-303',
    created_at: '2024-07-03T16:00:00Z',
    updated_at: '2024-07-04T10:15:00Z',
    client: mockClients[6],
    assigned_user: { email: 'analytics@empresa.com' }
  },
  {
    id: 24,
    title: 'Error en integración con API de terceros',
    description: 'La integración con la API de Google Analytics está fallando desde el último update.',
    status: 'open',
    priority: 'medium',
    client_id: 2,
    assigned_to: null,
    created_at: '2024-07-02T09:45:00Z',
    updated_at: '2024-07-02T09:45:00Z',
    client: mockClients[1],
    category: 'technical_issue'
  },
  {
    id: 25,
    title: 'Optimización de base de datos de clientes',
    description: 'La consulta de clientes tarda más de 30 segundos. Necesitamos optimizar los índices.',
    status: 'closed',
    priority: 'high',
    client_id: 7,
    assigned_to: 'user-404',
    created_at: '2024-06-25T11:20:00Z',
    updated_at: '2024-06-28T15:30:00Z',
    client: mockClients[6],
    assigned_user: { email: 'dba@empresa.com' }
  },
  {
    id: 26,
    title: 'Implementar sistema de chat en vivo',
    description: 'Solicitud de implementación de chat en vivo para atención al cliente en tiempo real.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 2,
    assigned_to: 'user-505',
    created_at: '2024-06-30T13:15:00Z',
    updated_at: '2024-07-03T11:45:00Z',
    client: mockClients[1],
    assigned_user: { email: 'frontend@empresa.com' },
    category: 'feature_request'
  },
  {
    id: 27,
    title: 'Error en módulo de facturación recurrente',
    description: 'Las facturas recurrentes no se están generando automáticamente cada mes.',
    status: 'open',
    priority: 'high',
    client_id: 7,
    assigned_to: null,
    created_at: '2024-07-04T08:30:00Z',
    updated_at: '2024-07-04T08:30:00Z',
    client: mockClients[6]
  },
  {
    id: 28,
    title: 'Configurar CDN para contenido estático',
    description: 'Implementar CDN para mejorar la velocidad de carga de imágenes y archivos estáticos.',
    status: 'open',
    priority: 'low',
    client_id: 2,
    assigned_to: null,
    created_at: '2024-06-28T16:20:00Z',
    updated_at: '2024-06-28T16:20:00Z',
    client: mockClients[1]
  },
  {
    id: 29,
    title: 'Actualizar framework a versión latest',
    description: 'Actualizar el framework del frontend de Vue 2 a Vue 3 para mejor rendimiento.',
    status: 'closed',
    priority: 'medium',
    client_id: 7,
    assigned_to: 'user-606',
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-06-22T14:30:00Z',
    client: mockClients[6],
    assigned_user: { email: 'senior-dev@empresa.com' }
  },
  {
    id: 30,
    title: 'Error en cálculo de métricas de conversión',
    description: 'Las métricas de conversión en el dashboard no coinciden con Google Analytics.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 2,
    assigned_to: 'user-707',
    created_at: '2024-07-01T15:30:00Z',
    updated_at: '2024-07-03T09:20:00Z',
    client: mockClients[1],
    assigned_user: { email: 'analyst@empresa.com' }
  },
  {
    id: 31,
    title: 'Implementar autenticación OAuth2',
    description: 'Solicitud de implementación de login con Google y Microsoft para facilitar el acceso.',
    status: 'open',
    priority: 'medium',
    client_id: 7,
    assigned_to: null,
    created_at: '2024-07-02T11:45:00Z',
    updated_at: '2024-07-02T11:45:00Z',
    client: mockClients[6]
  },
  {
    id: 32,
    title: 'Error en exportación de datos a Excel',
    description: 'La función de exportar reportes a Excel genera archivos corruptos.',
    status: 'open',
    priority: 'medium',
    client_id: 2,
    assigned_to: null,
    created_at: '2024-07-03T14:10:00Z',
    updated_at: '2024-07-03T14:10:00Z',
    client: mockClients[1]
  },
  {
    id: 33,
    title: 'Configurar backup automático en la nube',
    description: 'Implementar backups automáticos diarios en AWS S3 con retención de 90 días.',
    status: 'in_progress',
    priority: 'high',
    client_id: 7,
    assigned_to: 'user-808',
    created_at: '2024-06-29T08:15:00Z',
    updated_at: '2024-07-02T16:30:00Z',
    client: mockClients[6],
    assigned_user: { email: 'devops@empresa.com' }
  },
  {
    id: 34,
    title: 'Error en validación de formularios',
    description: 'Los formularios de contacto permiten envío de campos vacíos a pesar de las validaciones.',
    status: 'closed',
    priority: 'low',
    client_id: 2,
    assigned_to: 'user-909',
    created_at: '2024-06-26T13:20:00Z',
    updated_at: '2024-06-27T10:45:00Z',
    client: mockClients[1],
    assigned_user: { email: 'qa@empresa.com' }
  },
  {
    id: 35,
    title: 'Implementar búsqueda avanzada',
    description: 'Necesitamos implementar búsqueda avanzada con filtros múltiples y autocompletado.',
    status: 'open',
    priority: 'low',
    client_id: 7,
    assigned_to: null,
    created_at: '2024-07-01T09:30:00Z',
    updated_at: '2024-07-01T09:30:00Z',
    client: mockClients[6]
  },
  {
    id: 36,
    title: 'Error en sincronización con CRM',
    description: 'Los leads nuevos no se están sincronizando automáticamente con HubSpot.',
    status: 'in_progress',
    priority: 'high',
    client_id: 2,
    assigned_to: 'user-1010',
    created_at: '2024-07-03T10:45:00Z',
    updated_at: '2024-07-04T08:20:00Z',
    client: mockClients[1],
    assigned_user: { email: 'integration@empresa.com' }
  },
  {
    id: 37,
    title: 'Configurar alertas de monitoreo',
    description: 'Implementar alertas automáticas para CPU, memoria y espacio en disco.',
    status: 'open',
    priority: 'medium',
    client_id: 7,
    assigned_to: null,
    created_at: '2024-06-30T14:50:00Z',
    updated_at: '2024-06-30T14:50:00Z',
    client: mockClients[6]
  },
  {
    id: 38,
    title: 'Error en carga de imágenes',
    description: 'Las imágenes subidas no se redimensionan correctamente y ocupan mucho espacio.',
    status: 'closed',
    priority: 'medium',
    client_id: 2,
    assigned_to: 'user-1111',
    created_at: '2024-06-24T11:15:00Z',
    updated_at: '2024-06-26T15:20:00Z',
    client: mockClients[1],
    assigned_user: { email: 'media@empresa.com' }
  },
  {
    id: 39,
    title: 'Implementar API rate limiting',
    description: 'Necesitamos implementar límites de velocidad en la API para evitar abuso.',
    status: 'open',
    priority: 'medium',
    client_id: 7,
    assigned_to: null,
    created_at: '2024-07-02T16:40:00Z',
    updated_at: '2024-07-02T16:40:00Z',
    client: mockClients[6]
  },
  {
    id: 40,
    title: 'Error en generación de facturas PDF',
    description: 'Algunas facturas PDF se generan con formato incorrecto y caracteres especiales mal codificados.',
    status: 'in_progress',
    priority: 'high',
    client_id: 2,
    assigned_to: 'user-1212',
    created_at: '2024-07-04T12:25:00Z',
    updated_at: '2024-07-04T15:10:00Z',
    client: mockClients[1],
    assigned_user: { email: 'pdf-specialist@empresa.com' }
  },

  // ===== FREELANCER INDEPENDIENTE (company_id: 3) - Cliente: Carlos López (id: 3) =====
  {
    id: 41,
    title: 'Error 404 en página de contacto',
    description: 'La página de contacto está devolviendo error 404. Los usuarios no pueden enviar mensajes a través del formulario web.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-02T11:15:00Z',
    updated_at: '2024-07-02T11:15:00Z',
    client: mockClients[2]
  },
  {
    id: 42,
    title: 'Actualización de seguridad',
    description: 'Aplicar las últimas actualizaciones de seguridad y parches críticos al sistema.',
    status: 'closed',
    priority: 'high',
    client_id: 3,
    assigned_to: 'user-202',
    created_at: '2024-06-28T16:20:00Z',
    updated_at: '2024-07-01T14:45:00Z',
    client: mockClients[2],
    assigned_user: { email: 'security@empresa.com' }
  },
  {
    id: 43,
    title: 'Rediseño de sitio web',
    description: 'Actualizar el diseño del sitio web para que sea más moderno y responsive.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 3,
    assigned_to: 'user-301',
    created_at: '2024-06-25T10:30:00Z',
    updated_at: '2024-07-03T14:20:00Z',
    client: mockClients[2],
    assigned_user: { email: 'designer@empresa.com' }
  },
  {
    id: 44,
    title: 'Implementar SEO básico',
    description: 'Optimizar el sitio web para motores de búsqueda con meta tags y estructura correcta.',
    status: 'open',
    priority: 'medium',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-01T09:15:00Z',
    updated_at: '2024-07-01T09:15:00Z',
    client: mockClients[2]
  },
  {
    id: 45,
    title: 'Error en formulario de presupuestos',
    description: 'El formulario de solicitud de presupuestos no envía los datos correctamente.',
    status: 'open',
    priority: 'high',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-04T13:45:00Z',
    updated_at: '2024-07-04T13:45:00Z',
    client: mockClients[2]
  },
  {
    id: 46,
    title: 'Configurar Google Analytics',
    description: 'Instalar y configurar Google Analytics para seguimiento de visitantes.',
    status: 'closed',
    priority: 'low',
    client_id: 3,
    assigned_to: 'user-401',
    created_at: '2024-06-20T14:30:00Z',
    updated_at: '2024-06-22T16:15:00Z',
    client: mockClients[2],
    assigned_user: { email: 'analytics@empresa.com' }
  },
  {
    id: 47,
    title: 'Optimizar velocidad de carga',
    description: 'El sitio web tarda más de 5 segundos en cargar. Necesitamos optimización.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 3,
    assigned_to: 'user-501',
    created_at: '2024-07-02T08:20:00Z',
    updated_at: '2024-07-03T11:30:00Z',
    client: mockClients[2],
    assigned_user: { email: 'performance@empresa.com' }
  },
  {
    id: 48,
    title: 'Implementar blog personal',
    description: 'Añadir sección de blog para compartir artículos y mejorar SEO.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-06-30T15:45:00Z',
    updated_at: '2024-06-30T15:45:00Z',
    client: mockClients[2]
  },
  {
    id: 49,
    title: 'Error en galería de trabajos',
    description: 'Las imágenes de la galería no se muestran correctamente en móviles.',
    status: 'open',
    priority: 'medium',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-03T16:10:00Z',
    updated_at: '2024-07-03T16:10:00Z',
    client: mockClients[2]
  },
  {
    id: 50,
    title: 'Configurar certificado SSL',
    description: 'Instalar certificado SSL para que el sitio sea seguro (HTTPS).',
    status: 'closed',
    priority: 'high',
    client_id: 3,
    assigned_to: 'user-601',
    created_at: '2024-06-18T11:00:00Z',
    updated_at: '2024-06-19T09:30:00Z',
    client: mockClients[2],
    assigned_user: { email: 'sysadmin@empresa.com' }
  },
  {
    id: 51,
    title: 'Implementar sistema de citas online',
    description: 'Crear sistema para que clientes puedan agendar citas de consultoría online.',
    status: 'in_progress',
    priority: 'high',
    client_id: 3,
    assigned_to: 'user-701',
    created_at: '2024-07-01T12:15:00Z',
    updated_at: '2024-07-04T10:45:00Z',
    client: mockClients[2],
    assigned_user: { email: 'fullstack@empresa.com' }
  },
  {
    id: 52,
    title: 'Error en envío de emails de contacto',
    description: 'Los emails del formulario de contacto no llegan a la bandeja de entrada.',
    status: 'open',
    priority: 'high',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-04T09:25:00Z',
    updated_at: '2024-07-04T09:25:00Z',
    client: mockClients[2]
  },
  {
    id: 53,
    title: 'Añadir testimonios de clientes',
    description: 'Crear sección de testimonios para mostrar opiniones de clientes satisfechos.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-06-28T14:40:00Z',
    updated_at: '2024-06-28T14:40:00Z',
    client: mockClients[2]
  },
  {
    id: 54,
    title: 'Configurar backup del sitio web',
    description: 'Implementar backups automáticos semanales del sitio web y base de datos.',
    status: 'closed',
    priority: 'medium',
    client_id: 3,
    assigned_to: 'user-801',
    created_at: '2024-06-22T10:20:00Z',
    updated_at: '2024-06-24T15:50:00Z',
    client: mockClients[2],
    assigned_user: { email: 'backup@empresa.com' }
  },
  {
    id: 55,
    title: 'Implementar chat bot básico',
    description: 'Añadir chat bot para responder preguntas frecuentes automáticamente.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-02T17:30:00Z',
    updated_at: '2024-07-02T17:30:00Z',
    client: mockClients[2]
  },
  {
    id: 56,
    title: 'Error en carga de CV descargable',
    description: 'El enlace para descargar el CV en PDF no funciona correctamente.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 3,
    assigned_to: 'user-901',
    created_at: '2024-07-03T13:15:00Z',
    updated_at: '2024-07-04T11:20:00Z',
    client: mockClients[2],
    assigned_user: { email: 'frontend@empresa.com' }
  },
  {
    id: 57,
    title: 'Optimizar para móviles',
    description: 'Mejorar la experiencia de usuario en dispositivos móviles y tablets.',
    status: 'open',
    priority: 'medium',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-01T16:45:00Z',
    updated_at: '2024-07-01T16:45:00Z',
    client: mockClients[2]
  },
  {
    id: 58,
    title: 'Implementar integración con LinkedIn',
    description: 'Conectar el sitio web con el perfil de LinkedIn para mostrar experiencia actualizada.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-06-29T12:30:00Z',
    updated_at: '2024-06-29T12:30:00Z',
    client: mockClients[2]
  },
  {
    id: 59,
    title: 'Error en redirecciones',
    description: 'Algunas URLs antiguas no redirigen correctamente a las nuevas páginas.',
    status: 'closed',
    priority: 'low',
    client_id: 3,
    assigned_to: 'user-1001',
    created_at: '2024-06-26T09:40:00Z',
    updated_at: '2024-06-27T14:15:00Z',
    client: mockClients[2],
    assigned_user: { email: 'seo@empresa.com' }
  },
  {
    id: 60,
    title: 'Añadir mapa de ubicación',
    description: 'Incluir mapa de Google Maps en la página de contacto con la ubicación de la oficina.',
    status: 'open',
    priority: 'low',
    client_id: 3,
    assigned_to: null,
    created_at: '2024-07-04T15:20:00Z',
    updated_at: '2024-07-04T15:20:00Z',
    client: mockClients[2]
  },

  // ===== STARTUP INNOVADORA (company_id: 4) - Cliente: Ana Martínez (id: 4) =====
  {
    id: 61,
    title: 'Optimización de base de datos',
    description: 'Las consultas están siendo muy lentas en horas pico. Necesitamos optimizar las consultas más pesadas y revisar los índices.',
    status: 'in_progress',
    priority: 'high',
    client_id: 4,
    assigned_to: 'user-789',
    created_at: '2024-07-01T15:45:00Z',
    updated_at: '2024-07-03T09:20:00Z',
    client: mockClients[3],
    assigned_user: { email: 'dba@empresa.com' }
  },
  {
    id: 62,
    title: 'Implementar sistema de notificaciones push',
    description: 'Necesitamos notificaciones push para la aplicación móvil de la startup.',
    status: 'open',
    priority: 'medium',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-03T11:30:00Z',
    updated_at: '2024-07-03T11:30:00Z',
    client: mockClients[3]
  },
  {
    id: 63,
    title: 'Error en sistema de pagos',
    description: 'Los pagos con tarjeta de crédito están fallando intermitentemente.',
    status: 'open',
    priority: 'high',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-04T14:20:00Z',
    updated_at: '2024-07-04T14:20:00Z',
    client: mockClients[3]
  },
  {
    id: 64,
    title: 'Desarrollar API REST v2',
    description: 'Crear nueva versión de la API con mejor documentación y endpoints más eficientes.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1102',
    created_at: '2024-06-28T10:15:00Z',
    updated_at: '2024-07-02T16:30:00Z',
    client: mockClients[3],
    assigned_user: { email: 'api-dev@empresa.com' }
  },
  {
    id: 65,
    title: 'Implementar analytics avanzados',
    description: 'Integrar herramientas de analytics para tracking detallado del comportamiento de usuarios.',
    status: 'open',
    priority: 'medium',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-02T13:45:00Z',
    updated_at: '2024-07-02T13:45:00Z',
    client: mockClients[3]
  },
  {
    id: 66,
    title: 'Error en proceso de registro',
    description: 'Algunos usuarios no pueden completar el registro debido a errores de validación.',
    status: 'in_progress',
    priority: 'high',
    client_id: 4,
    assigned_to: 'user-1203',
    created_at: '2024-07-03T09:10:00Z',
    updated_at: '2024-07-04T12:25:00Z',
    client: mockClients[3],
    assigned_user: { email: 'auth@empresa.com' }
  },
  {
    id: 67,
    title: 'Configurar CI/CD pipeline',
    description: 'Implementar pipeline de integración y despliegue continuo para acelerar releases.',
    status: 'closed',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1304',
    created_at: '2024-06-25T14:00:00Z',
    updated_at: '2024-06-30T11:45:00Z',
    client: mockClients[3],
    assigned_user: { email: 'devops@empresa.com' }
  },
  {
    id: 68,
    title: 'Implementar sistema de chat grupal',
    description: 'Desarrollar funcionalidad de chat grupal para equipos dentro de la aplicación.',
    status: 'open',
    priority: 'low',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-01T16:20:00Z',
    updated_at: '2024-07-01T16:20:00Z',
    client: mockClients[3]
  },
  {
    id: 69,
    title: 'Error en sincronización de datos',
    description: 'Los datos no se sincronizan correctamente entre la web y la app móvil.',
    status: 'open',
    priority: 'high',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-04T10:30:00Z',
    updated_at: '2024-07-04T10:30:00Z',
    client: mockClients[3]
  },
  {
    id: 70,
    title: 'Optimizar algoritmo de recomendaciones',
    description: 'Mejorar el algoritmo de machine learning para recomendaciones más precisas.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1405',
    created_at: '2024-06-30T09:45:00Z',
    updated_at: '2024-07-03T14:10:00Z',
    client: mockClients[3],
    assigned_user: { email: 'ml@empresa.com' }
  },
  {
    id: 71,
    title: 'Implementar dark mode',
    description: 'Añadir tema oscuro a la aplicación según preferencias del usuario.',
    status: 'open',
    priority: 'low',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-02T11:15:00Z',
    updated_at: '2024-07-02T11:15:00Z',
    client: mockClients[3]
  },
  {
    id: 72,
    title: 'Error en exportación de reportes',
    description: 'Los reportes exportados a PDF contienen datos incorrectos o incompletos.',
    status: 'closed',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1506',
    created_at: '2024-06-27T13:30:00Z',
    updated_at: '2024-06-29T15:20:00Z',
    client: mockClients[3],
    assigned_user: { email: 'reports@empresa.com' }
  },
  {
    id: 73,
    title: 'Configurar monitoreo de rendimiento',
    description: 'Implementar herramientas de monitoring para detectar problemas de rendimiento.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1607',
    created_at: '2024-07-01T08:20:00Z',
    updated_at: '2024-07-03T16:40:00Z',
    client: mockClients[3],
    assigned_user: { email: 'monitoring@empresa.com' }
  },
  {
    id: 74,
    title: 'Implementar sistema de gamificación',
    description: 'Añadir elementos de gamificación para aumentar engagement de usuarios.',
    status: 'open',
    priority: 'low',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-06-29T15:50:00Z',
    updated_at: '2024-06-29T15:50:00Z',
    client: mockClients[3]
  },
  {
    id: 75,
    title: 'Error en validación de formularios complejos',
    description: 'Los formularios con múltiples pasos no validan correctamente todos los campos.',
    status: 'open',
    priority: 'medium',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-03T17:15:00Z',
    updated_at: '2024-07-03T17:15:00Z',
    client: mockClients[3]
  },
  {
    id: 76,
    title: 'Implementar búsqueda con filtros avanzados',
    description: 'Mejorar el sistema de búsqueda con filtros por múltiples criterios.',
    status: 'open',
    priority: 'medium',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-01T14:25:00Z',
    updated_at: '2024-07-01T14:25:00Z',
    client: mockClients[3]
  },
  {
    id: 77,
    title: 'Error en carga de archivos multimedia',
    description: 'Los videos y imágenes grandes no se suben correctamente a la plataforma.',
    status: 'in_progress',
    priority: 'high',
    client_id: 4,
    assigned_to: 'user-1708',
    created_at: '2024-07-02T12:40:00Z',
    updated_at: '2024-07-04T09:15:00Z',
    client: mockClients[3],
    assigned_user: { email: 'media@empresa.com' }
  },
  {
    id: 78,
    title: 'Configurar CDN global',
    description: 'Implementar CDN para mejorar velocidad de carga en diferentes regiones.',
    status: 'closed',
    priority: 'medium',
    client_id: 4,
    assigned_to: 'user-1809',
    created_at: '2024-06-24T10:30:00Z',
    updated_at: '2024-06-26T14:45:00Z',
    client: mockClients[3],
    assigned_user: { email: 'infrastructure@empresa.com' }
  },
  {
    id: 79,
    title: 'Implementar sistema de referidos',
    description: 'Crear programa de referidos para que usuarios inviten a otros usuarios.',
    status: 'open',
    priority: 'low',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-04T16:10:00Z',
    updated_at: '2024-07-04T16:10:00Z',
    client: mockClients[3]
  },
  {
    id: 80,
    title: 'Error en cálculos estadísticos',
    description: 'Los dashboards muestran estadísticas incorrectas en algunos gráficos.',
    status: 'open',
    priority: 'medium',
    client_id: 4,
    assigned_to: null,
    created_at: '2024-07-03T15:35:00Z',
    updated_at: '2024-07-03T15:35:00Z',
    client: mockClients[3]
  },

  // ===== CONSULTING PRO (company_id: 5) - Cliente: Roberto Sánchez (id: 5) =====
  {
    id: 81,
    title: 'Integración con API externa',
    description: 'Implementar integración con la API de pagos para automatizar el proceso de facturación y cobro.',
    status: 'open',
    priority: 'medium',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-02T08:15:00Z',
    updated_at: '2024-07-02T08:15:00Z',
    client: mockClients[4]
  },
  {
    id: 82,
    title: 'Desarrollar portal de clientes',
    description: 'Crear portal web donde los clientes puedan ver el estado de sus proyectos.',
    status: 'in_progress',
    priority: 'high',
    client_id: 5,
    assigned_to: 'user-1910',
    created_at: '2024-07-01T10:30:00Z',
    updated_at: '2024-07-03T14:45:00Z',
    client: mockClients[4],
    assigned_user: { email: 'portal-dev@empresa.com' }
  },
  {
    id: 83,
    title: 'Error en sistema de tiempo y costos',
    description: 'El sistema de tracking de tiempo no calcula correctamente los costos por proyecto.',
    status: 'open',
    priority: 'high',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-04T11:20:00Z',
    updated_at: '2024-07-04T11:20:00Z',
    client: mockClients[4]
  },
  {
    id: 84,
    title: 'Implementar sistema CRM avanzado',
    description: 'Mejorar el CRM actual con funcionalidades de pipeline de ventas y automatización.',
    status: 'open',
    priority: 'medium',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-06-30T15:40:00Z',
    updated_at: '2024-06-30T15:40:00Z',
    client: mockClients[4]
  },
  {
    id: 85,
    title: 'Error en generación de propuestas',
    description: 'Las propuestas comerciales no se generan con el formato correcto desde la plantilla.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 5,
    assigned_to: 'user-2011',
    created_at: '2024-07-02T13:15:00Z',
    updated_at: '2024-07-04T10:30:00Z',
    client: mockClients[4],
    assigned_user: { email: 'proposals@empresa.com' }
  },
  {
    id: 86,
    title: 'Configurar integración con contabilidad',
    description: 'Conectar el sistema con el software contable para sincronización automática.',
    status: 'closed',
    priority: 'medium',
    client_id: 5,
    assigned_to: 'user-2112',
    created_at: '2024-06-26T09:45:00Z',
    updated_at: '2024-06-29T16:20:00Z',
    client: mockClients[4],
    assigned_user: { email: 'accounting@empresa.com' }
  },
  {
    id: 87,
    title: 'Implementar dashboard ejecutivo',
    description: 'Crear dashboard con KPIs principales para la dirección de la consultora.',
    status: 'open',
    priority: 'medium',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-03T09:25:00Z',
    updated_at: '2024-07-03T09:25:00Z',
    client: mockClients[4]
  },
  {
    id: 88,
    title: 'Error en calendario de recursos',
    description: 'El calendario no muestra correctamente la disponibilidad de consultores.',
    status: 'open',
    priority: 'high',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-04T14:50:00Z',
    updated_at: '2024-07-04T14:50:00Z',
    client: mockClients[4]
  },
  {
    id: 89,
    title: 'Optimizar reportes de proyectos',
    description: 'Los reportes de estado de proyectos tardan mucho en generarse.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 5,
    assigned_to: 'user-2213',
    created_at: '2024-07-01T16:10:00Z',
    updated_at: '2024-07-03T12:35:00Z',
    client: mockClients[4],
    assigned_user: { email: 'reports@empresa.com' }
  },
  {
    id: 90,
    title: 'Implementar firma digital',
    description: 'Añadir funcionalidad de firma digital para contratos y documentos legales.',
    status: 'open',
    priority: 'low',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-06-28T12:45:00Z',
    updated_at: '2024-06-28T12:45:00Z',
    client: mockClients[4]
  },
  {
    id: 91,
    title: 'Error en notificaciones por email',
    description: 'Las notificaciones automáticas de vencimientos no se envían a tiempo.',
    status: 'open',
    priority: 'high',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-03T17:30:00Z',
    updated_at: '2024-07-03T17:30:00Z',
    client: mockClients[4]
  },
  {
    id: 92,
    title: 'Configurar backup en múltiples ubicaciones',
    description: 'Implementar estrategia de backup distribuido para mayor seguridad de datos.',
    status: 'closed',
    priority: 'high',
    client_id: 5,
    assigned_to: 'user-2314',
    created_at: '2024-06-23T08:30:00Z',
    updated_at: '2024-06-25T15:45:00Z',
    client: mockClients[4],
    assigned_user: { email: 'backup@empresa.com' }
  },
  {
    id: 93,
    title: 'Implementar sistema de facturación automática',
    description: 'Automatizar la generación de facturas basada en horas trabajadas y milestones.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 5,
    assigned_to: 'user-2415',
    created_at: '2024-06-29T11:20:00Z',
    updated_at: '2024-07-02T14:15:00Z',
    client: mockClients[4],
    assigned_user: { email: 'billing@empresa.com' }
  },
  {
    id: 94,
    title: 'Error en cálculo de rentabilidad',
    description: 'Los cálculos de rentabilidad por proyecto no incluyen todos los costos indirectos.',
    status: 'open',
    priority: 'medium',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-02T10:55:00Z',
    updated_at: '2024-07-02T10:55:00Z',
    client: mockClients[4]
  },
  {
    id: 95,
    title: 'Implementar chat interno para equipo',
    description: 'Sistema de chat interno para comunicación rápida entre consultores.',
    status: 'open',
    priority: 'low',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-01T13:40:00Z',
    updated_at: '2024-07-01T13:40:00Z',
    client: mockClients[4]
  },
  {
    id: 96,
    title: 'Error en importación de datos',
    description: 'La importación masiva de datos desde Excel no procesa correctamente algunos campos.',
    status: 'in_progress',
    priority: 'medium',
    client_id: 5,
    assigned_to: 'user-2516',
    created_at: '2024-07-03T08:45:00Z',
    updated_at: '2024-07-04T13:20:00Z',
    client: mockClients[4],
    assigned_user: { email: 'data@empresa.com' }
  },
  {
    id: 97,
    title: 'Configurar alertas de presupuesto',
    description: 'Alertas automáticas cuando los proyectos superan el 80% del presupuesto.',
    status: 'open',
    priority: 'medium',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-06-27T15:25:00Z',
    updated_at: '2024-06-27T15:25:00Z',
    client: mockClients[4]
  },
  {
    id: 98,
    title: 'Implementar módul de recursos humanos',
    description: 'Sistema para gestión de perfiles, evaluaciones y desarrollo de consultores.',
    status: 'open',
    priority: 'low',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-04T12:15:00Z',
    updated_at: '2024-07-04T12:15:00Z',
    client: mockClients[4]
  },
  {
    id: 99,
    title: 'Error en sincronización con calendario',
    description: 'Las citas del sistema no se sincronizan correctamente con Outlook.',
    status: 'open',
    priority: 'high',
    client_id: 5,
    assigned_to: null,
    created_at: '2024-07-04T16:35:00Z',
    updated_at: '2024-07-04T16:35:00Z',
    client: mockClients[4]
  },
  {
    id: 100,
    title: 'Implementar sistema de knowledge base',
    description: 'Base de conocimientos interna para documentar metodologías y best practices.',
    status: 'closed',
    priority: 'low',
    client_id: 5,
    assigned_to: 'user-2617',
    created_at: '2024-06-21T14:10:00Z',
    updated_at: '2024-06-24T11:30:00Z',
    client: mockClients[4],
    assigned_user: { email: 'knowledge@empresa.com' }
  }
]

// Usuarios mock para autenticación
export const mockAdminUser: MockUser = {
  id: 'mock-admin-123',
  email: 'admin@sistema-tickets.com',
  role: 'admin',
  user_metadata: {
    name: 'Usuario Admin'
  }
}

export const mockClientUsers: ClientUser[] = [
  {
    id: 'mock-client-1',
    email: 'juan.perez@empresa-a.com',
    role: 'client',
    client_id: 1,
    client_data: mockClients[0],
    user_metadata: {
      name: 'Juan Pérez'
    }
  },
  {
    id: 'mock-client-2', 
    email: 'maria.garcia@techcorp.com',
    role: 'client',
    client_id: 2,
    client_data: mockClients[1],
    user_metadata: {
      name: 'María García'
    }
  },
  {
    id: 'mock-client-3',
    email: 'carlos.lopez@freelancer.com', 
    role: 'client',
    client_id: 3,
    client_data: mockClients[2],
    user_metadata: {
      name: 'Carlos López'
    }
  },
  {
    id: 'mock-client-4',
    email: 'pedro.rodriguez@empresa-a.com',
    role: 'client',
    client_id: 6,
    client_data: mockClients[5],
    user_metadata: {
      name: 'Pedro Rodríguez'
    }
  },
  {
    id: 'mock-client-5',
    email: 'laura.fernandez@techcorp.com',
    role: 'client',
    client_id: 7,
    client_data: mockClients[6],
    user_metadata: {
      name: 'Laura Fernández'
    }
  }
]

// Para compatibilidad hacia atrás
export const mockUser = mockAdminUser

// Funciones utilitarias para el modo mock
export const delay = (ms: number): Promise<void> => 
  new Promise(resolve => setTimeout(resolve, ms))

export const shouldSimulateError = (): boolean => Math.random() < 0.001 // Reducido a 0.1% de probabilidad

export const generateId = (): number => Date.now() + Math.floor(Math.random() * 1000) 